name: Release test-app

on:
    push:
        branches:
            - main
        paths:
            - 'app/test-app/**'

jobs:
    release:
        permissions:
            contents: write # to be able to publish a GitHub release
            issues: write # to be able to comment on released issues
            pull-requests: write # to be able to comment on released pull requests
            id-token: write # to enable use of OIDC for npm provenance
        uses: ./.github/workflows/release-base.yml
        with:
            dir: 'app/test-app'
        secrets: inherit
