name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  # Job to merge release PR to main and update packages versions
  release-please:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.release.outputs }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          # this assumes that you have created a personal access token
          # (PAT) and configured it as a GitHub action secret named
          # `MY_RELEASE_PLEASE_TOKEN` (this secret name is not important).
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
  
  publish-to-npm:
    needs: release-please
    # Only trigger after release-please managed PR from previous step is merged to main.
    if: ${{ fromJson(needs.release-please.outputs.result.releases_created) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          #   scope: '@viktorsaws'
      - name: Install dependencies
        run: npm clean-install
      - name: Test
        run: npm run test
      - name: Package deployment artifacts
        run: npm run package
      - run: npm publish --workspace app/test-app
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: ${{ needs.release-please.outputs.result['app/test-app--release_created'] }}
      - run: npm publish --workspace app/second-app
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: ${{ needs.release-please.outputs.result['app/second-app--release_created'] }}
      - run: npm publish --workspace server/test-lsp
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: ${{ needs.release-please.outputs.result['server/test-lsp--release_created'] }}