name: Release test-lsp server

on:
    push:
        branches:
            - main
        paths:
            - 'server/test-lsp/**'
    workflow_run:
        workflows: ['Test workflow']
        types: [completed]

jobs:
    release:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        permissions:
            contents: write # to be able to publish a GitHub release
            issues: write # to be able to comment on released issues
            pull-requests: write # to be able to comment on released pull requests
            id-token: write # to enable use of OIDC for npm provenance
        uses: ./.github/workflows/release-base.yml
        with:
            dir: 'server/test-lsp'
        secrets: inherit
