name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
        if: ${{ fromJson(steps.release.outputs.releases_created) }}
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          #   scope: '@viktorsaws'
        if: ${{ fromJson(steps.release.outputs.releases_created) }}
      - name: Set token
        run: echo "NODE_AUTH_TOKEN=${{ secrets.NPM_TOKEN }}" >> $GITHUB_ENV
        if: ${{ fromJson(steps.release.outputs.releases_created) }}
      - name: Install dependencies
        run: npm clean-install
        if: ${{ fromJson(steps.release.outputs.releases_created) }}
      - name: Test
        run: npm run test
        if: ${{ fromJson(steps.release.outputs.releases_created) }}
      - name: Package deployment artifacts
        run: npm run package
        if: ${{ fromJson(steps.release.outputs.releases_created) }}
      - run: npm publish --workspace app/test-app
        if: ${{ steps.release.outputs['app/test-app--release_created'] }}
      - run: npm publish --workspace app/second-app
        if: ${{ steps.release.outputs['app/second-app--release_created'] }}
      - run: npm publish --workspace server/test-lsp
        if: ${{ steps.release.outputs['server/test-lsp--release_created'] }}