name: Release test-server

on:
    push:
        branches:
            - main
        paths:
            - 'server/test-server/**'

jobs:
    release:
        uses: ./.github/workflows/release-base.yml
        with:
            dir: 'server/test-server'
        secrets: inherit
