name: Release All Packages

# Disable commit hooks in CI
env:
  HUSKY: 0

on:
    push:
        branches:
            - main
        paths:
            - 'app/test-app/**'
            - 'server/test-lsp/**'

# Allow only 1 pending workflow run to be scheduled
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        permissions:
            contents: write # to be able to publish a GitHub release
            issues: write # to be able to comment on released issues
            pull-requests: write # to be able to comment on released pull requests
            id-token: write # to enable use of OIDC for npm provenance
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  persist-credentials: false
            - uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
                  registry-url: 'https://registry.npmjs.org'
                #   scope: '@viktorsaws'
            - name: Install dependencies
              run: npm clean-install
            - name: Test
              run: npm run test
            - name: Package deployment artifacts
              run: npm run package
            - name: Release Test App
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: |
                  cd app/test-app
                  npx semantic-release
            - name: Release Test LSP Server
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: |
                  cd server/test-lsp
                  npx semantic-release
