name: Reusable Release workflow

on:
    workflow_call:
        inputs:
            dir:
                required: true
                type: string

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        permissions:
            contents: write # to be able to publish a GitHub release
            issues: write # to be able to comment on released issues
            pull-requests: write # to be able to comment on released pull requests
            id-token: write # to enable use of OIDC for npm provenance
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  persist-credentials: false
            - uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
                  registry-url: 'https://registry.npmjs.org'
                #   scope: '@viktorsaws'
            - name: Install dependencies
              run: npm clean-install
            # - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
            #   run: npm audit signatures
            - name: Test
              run: npm run test
            - name: Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: |
                  cd ${{ inputs.dir }}
                  npx semantic-release
