name: Release test-app

on:
    push:
        branches:
            - main
        paths:
            - 'app/test-app/**'
jobs:
    release:
        uses: ./.github/workflows/release-base.yaml
        with:
            dir: 'app/test-app'
        secrets: inherit
