name: Test workflow
on:
    push:
        branches: [main, dev, feature/*]
    pull_request:
        branches: [main, dev, feature/*]

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Sync Code
              uses: actions/checkout@v4
            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: Build
              run: npm clean-install
            - name: Test
              run: npm run test
